version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@nestjs/websockets"
    versions:
    - 7.6.13
    - 7.6.7
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.1.0
  - dependency-name: "@nrwl/workspace"
    versions:
    - 11.2.6
    - 11.4.0
  - dependency-name: "@nestjs/platform-express"
    versions:
    - 7.6.13
    - 7.6.7
  - dependency-name: "@nrwl/tao"
    versions:
    - 11.2.6
    - 11.4.0
  - dependency-name: "@nrwl/node"
    versions:
    - 11.2.6
    - 11.4.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: supertest
    versions:
    - 6.1.3
  - dependency-name: class-validator
    versions:
    - 0.13.1
  - dependency-name: "@stechy1/schematics"
    versions:
    - 1.0.1
