name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run affected:lint
    - name: Check in-module circular imports
      run: npm run tool:check-imports
    - name: Build
      run: npm run build
    - name: Unit Tests
      run: npm run test:cov
#    - name: E2E Tests
#      run: npm run test:e2e:cov
    - name: Merge code coverage
      run: npm run tool:merge-coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
